name: mdpert
channels:
  - conda-forge
  - pypi
dependencies:
  - python=3.7
  - pandas
  - parmed
  - biopython
  - freeglut
  - glew
  - matplotlib
  - mdtraj
  - networkx
  - numpy
  - openmm
  - pdbfixer
  - prody
  - pymol-open-source
  - pyopengl
  - pyqtgraph
  - pyside2
  - pystache
  - pyvis



