package:
  name: mdpertool
  version: 0.0.1

source:
  url: https://github.com/Bio-Otto/MDPerTool_GUI.git
  sha256: b1fbb8193e9a75736ad3eaa9f53cdab0fe53d5b3c26bc1ac48f67a5b71ed56ca

build:
  noarch: python
  number: 0

requirements:
  host:
    - pip
    - python >=3.7

  run:
    - python >=3.7
    - setuptools
    - conda-forge::numpy
    - conda-forge::openmm
    - biopython
    - matplotlib
    - conda-forge::mdtraj
    - networkx
    - pandas
    - conda-forge::parmed
    - conda-forge::pdbfixer
    - conda-forge::prody
    - conda-forge::pymol-open-source
    - pyopengl
    - conda-forge::pyqtgraph
    - pyqtwebengine
    - conda-forge::pyside2
    - pystache
    - pyvis

test:
  requires:
    - pytest

  commands:
    # Activate test environment
    - conda create -n test_env python=%PY_VER% --file %RECIPE_DIR%/requirements.txt
    - conda activate test_env
    - pip install .

about:
  home: "https://github.com/Bio-Otto/MDPerTool_GUI"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Software Tool for Investigation of Allosteric Communication within Proteins via Energy Dissipation Concept
  description: The Program applying Energy Dissipation Concept using powerful OpenMM Molecular Dynamic Toolkit, which also supports the Cuda platform. Each residual energy calculation required for the concept can be calculated using OpenMMs flexible and useful infrastructure.In addition, you can use the package only for energy decomposition. For this, it will be sufficient to specify a XTC or a DCD file in the script.
  dev_url: https://github.com/Bio-Otto/MDPerTool_GUI

extra:
  recipe-maintainers:
    - Bio-Otto
  upload: main

script:
  - python setup.py install

entry_points:
  - mdpertool = mdpertool.ui_main:run_mdpertool
