package:
  name: mdpertool
  version: 0.0.1

source:
  git_url: https://github.com/Bio-Otto/MDPerTool_GUI.git
  sha256: b1fbb8193e9a75736ad3eaa9f53cdab0fe53d5b3c26bc1ac48f67a5b71ed56ca
  path: ..

build:
  number: 0 # Build number and string do not work together.
  noarch: python
  #preserve_egg_dir: True
  #skip: True  # [win or py2k]
  #script: python setup.py install --single-version-externally-managed --record=record.txt
  script: {{ PYTHON }} setup.py install
  #entry_points:
  #  - mdpertool = mdpertool.__main__:main


requirements:

  host:
    - pip
    - python ==3.7

  run:
    - python ==3.7
    - setuptools
    - numpy
    - openmm
    - biopython
    - matplotlib
    - mdtraj
    - networkx
    - openmm
    - pandas
    - parmed
    - pdbfixer
    - prody
    - pymol-open-source
    - pyopengl
    - pyqtgraph
    - pyqtwebengine
    - pyside2
    - pystache
    - pyvis

test:
  imports:
    - mdpertool

  requires:
    - pytest

  commands:
    - pytest -vv --pyargs mdpertool

about:
  home: "https://github.com/Bio-Otto/MDPerTool_GUI"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Software Tool for Investigation of Allosteric Communication within Proteins via Energy Dissipation Concept
  description: The Program applying Energy Dissipation Concept using powerfull OpenMM Molecular Dynamic Toolkit, which also supports the Cuda platform. Each residual energy calculation required for the concept can be calculated using OpenMMs flexible and useful infrastructure.In addition, you can use the package only for energy decomposition. For this, it will be sufficient to specify a XTC or a DCD file in the script.
  dev_url: https://github.com/Bio-Otto/MDPerTool_GUI

extra:
  recipe-maintainers:
    - Bio-Otto
  upload: main # Upload to anaconda with the "main" label.