package:
  name: mdpertool
  version: 0.0.1

source:
  git_url: https://github.com/Bio-Otto/MDPerTool_GUI.git
  sha256: b1fbb8193e9a75736ad3eaa9f53cdab0fe53d5b3c26bc1ac48f67a5b71ed56ca
  path: ..

extra:
  upload: main # Upload to anaconda with the "main" label.


build:
  preserve_egg_dir: True
  number: 0 # Build number and string do not work together.
  #skip: True  # [win or py2k]
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - mdpertool = mdpertool.__main__:main


requirements:
  build:
    - python
    - setuptools
    - numpy
    - openmm
    - biopython
    - matplotlib
    - mdtraj
    - networkx
    - openmm
    - pandas
    - parmed
    - pdbfixer
    - prody
    - pymol-open-source
    - pyopengl
    - pyqtgraph
    - pyqtwebengine
    - pyside2=5.13.2
    - pystache
    - pyvis


  run:
    - python
    - setuptools
    - numpy
    - openmm
    - biopython
    - matplotlib
    - mdtraj
    - networkx
    - openmm
    - pandas
    - parmed
    - pdbfixer
    - prody
    - pymol-open-source
    - pyopengl
    - pyqtgraph
    - pyqtwebengine
    - pyside2=5.13.2
    - pystache
    - pyvis

test:
  imports:
    - mdpertool

  requires:
    - pytest

  commands:
    - pytest -vv --pyargs mdpertool

about:
  home: https://github.com/Bio-Otto/MDPerTool_GUI
  license: BSD 3-Clause
  license_file: LICENSE.md
  license_family: BSD
  summary: {{ description }}
  description: A Software Tool for Investigation of Allosteric Communication within Protein Structures via Energy Dissipation in Molecular Dynamics Simulations
