{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}
{% set description = data.get("description") %}
{% set long_description = data.get("long_description") %}
{% set url = data.get("url") %}
{% set version = data.get("version") %}


package:
  name: mdpertool
  version: "{{ version }}"

source:
  git_url: https://github.com/Bio-Otto/MDPerTool_GUI.git
  sha256: b1fbb8193e9a75736ad3eaa9f53cdab0fe53d5b3c26bc1ac48f67a5b71ed56ca
  path: ..

extra:
  channels:
    - conda-forge

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - mdpertool = mdpertool.__main__:main


requirements:
  host:
    - python >=3.7
    - pip

  build:
    - setuptools
    - numpy


  run:

    - biopython=1.79
    - cudatoolkit=11.5
    - fftw=3.3
    - glew=2.1
    - matplotlib=3.5
    - mdtraj=1.9.7
    - networkx=2.6.3
    - numpy=1.21.4
    - openmm=7.6.0
    - pandas=1.3.4
    - parmed=3.4.3
    - pdbfixer=1.8.1
    - pip=21.2.4
    - pmw=2.0.1
    - prody=2.0
    - pymol-open-source=2.5.0
    - pyopengl=3.1.5
    - pyqt=5.12.3
    - pyqt-impl=5.12.3
    - pyqtgraph=0.12.3
    - pyqtwebengine=5.12.1
    - pyside2=5.13.2
    - pystache=0.5.4
    - python=3.7.11
    - pyvis=0.1.9
    - qt=5.12.9
    - scipy=1.7.3
    - setuptools=58.0.4
    - xz=5.2.5
    - zipp=3.6.0
    - zlib=1.2.11
    - zstd=1.5.0

test:
  imports:
    - mdpertool

  requires:
    - pytest

  commands:
    - pytest -vv --pyargs mdpertool

about:
  home: "{{ url }}"
  license: BSD 3-Clause
  license_file: LICENSE.md
  license_family: BSD

  summary: {{ description }}
  description: "{{ long_description }}"
  dev_url: "{{ url }}"
  #doc_url: https://bio-otto.github.io/Bio-Otto/MDPerTool_GUI