{% set data = load_setup_py_data() %}
{% set name = "mdpertool" %}
{% set version = "0.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

channels:
  - conda-forge
  - defaults

source:
  path: ..

build:
  number: 0
  noarch: python
  script:
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -v"

requirements:
  host:
    - pip
    - python >=3.11
    - parmed
    - openmm
    - pdbfixer
    - pyside2
    - pyqtgraph
    - pystache
    - prody
    - mdanalysis
    - mdtraj

  run:
    - python >=3.11
    - networkx
    - pandas
    - biopython
    - pyopengl
    - pyqtwebengine
    - pyyaml
    - cudatoolkit >=11.1
    - matplotlib
    - pyvis


test:
  imports:
    - mdpertool

about:
  home: "https://github.com/Bio-Otto/MDPerTool_GUI"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Perturbation based Allosteric Pathway Finder"

extra:
  recipe-maintainers:
    - Bio-Otto
