{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: mdpertool
  version: {{ data.get('version') }}

source:
  git_url: https://github.com/Bio-Otto/MDPerTool_GUI.git
  sha256: b1fbb8193e9a75736ad3eaa9f53cdab0fe53d5b3c26bc1ac48f67a5b71ed56ca
  path: ..

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - processrcmfolder = mdpertool.dataprocessing:process_folder


requirements:
  build:
    noarch: python
    - setuptools

  run:
    - python >=3.7
    - mdtraj
    - pyyaml
    - matplotlib
    - pyvis
    - openmm
    - pyqtgraph
    - prody
    - pymol-open-source
    - pyopengl
    - networkx
    - parmed
    - pdbfixer
    - prody
    - pyside2
    - pystache

test:
  imports:
    - mdpertool

  requires:
    - pytest >=3.0.0
    - pytest-cov >=2.3.1

  commands:
    - pytest -vv --pyargs mdpertool

about:
  home: {{ data.get('url') }}
  license: BSD 3-Clause
  license_file: LICENSE.md
  license_family: BSD

  summary: {{ data.get('description') }}
  description: {{ data.get('long_description') }}
  #doc_url: https://bio-otto.github.io/Bio-Otto/MDPerTool_GUI
  dev_url: {{ data.get('url') }}
