
{% set name = "mdpertool" %}
{% set version = "0.0.8" %}


package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

channels:
  - conda-forge
  - defaults

source:
  #git_url: https://github.com/Bio-Otto/MDPerTool_GUI.git
  #sha256: b1fbb8193e9a75736ad3eaa9f53cdab0fe53d5b3c26bc1ac48f67a5b71ed56ca
  path: ..

build:
  noarch: python
  #preserve_egg_dir: True
  number: 0
  #skip: True  # [win or py2k]
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - mdpertool = mdpertool.launcher:run_mdpertool


requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python >=3.10,<3.13
    - setuptools <70.0.0
    - lxml
    - pyside2 >=5.15,<6
    - matplotlib
    - pandas
    - pyqtgraph
    - openmm >=8.5,<8.6
    - networkx
    - pdbfixer
    - pyopengl
    - pymol-open-source >=2.5
    - biopython
    - prody
    - pyqtwebengine
    - pyyaml
    - pystache
    - parmed
    - mdtraj >=1.9.7
    - mdanalysis
    #- pyvis


#test:
#  imports:
#    - mdpertool

#  commands:
#    - mdpertool -gui

test:
  requires:
    - pytest

  commands:
    - mdpertool --help
    - mdpertool cli --help
    - mdpertool gui --help
    python -c "from mdpertool._version import __version__; assert __version__ == '0.0.8'"
  imports:
    - mdpertool



about:
  home: "https://github.com/Bio-Otto/MDPerTool_GUI"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "A Software Tool for Investigation of Allosteric Communication within Proteins via Energy Dissipation Concept"
  description: |
    The Program applying Energy Dissipation Concept using powerfull OpenMM Molecular Dynamic Toolkit, which also supports the Cuda platform.
    
    IMPORTANT INSTALLATION INSTRUCTION:
    Anaconda's default install command might miss required dependencies. To install this package correctly, please run the following command in your terminal:
    
    conda create -n mdpertool -c conda-forge -c bio-otto python=3.11 mdpertool
    
  dev_url: "https://github.com/Bio-Otto/MDPerTool_GUI"

extra:
  recipe-maintainers:
    - Bio-Otto
