{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}
{% set description = data.get("description") %}
{% set long_description = data.get("long_description") %}
{% set url = data.get("url") %}
{% set version = data.get("version") %}


package:
  name: mdpertool
  version: "{{ version }}"

source:
  git_url: https://github.com/Bio-Otto/MDPerTool_GUI.git
  sha256: b1fbb8193e9a75736ad3eaa9f53cdab0fe53d5b3c26bc1ac48f67a5b71ed56ca
  path: ..

extra:
  channels:
    - conda-forge

build:
  number: 0
  skip: True  # [win or py2k]
  preserve_egg_dir: True
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - mdpertool = mdpertool.__main__:main


requirements:
  build:
    - python
    - setuptools
    - numpy >=1.14
    - openmm >=7.5.0
    - biopython
    - matplotlib
    - mdtraj
    - networkx >=2.0
    - openmm
    - pandas
    - parmed
    - pdbfixer
    - prody
    - pymol-open-source
    - pyopengl
    - pyqtgraph
    - pyqtwebengine
    - pyside2=5.13.2
    - pystache
    - pyvis


  run:
    - python
    - setuptools
    - numpy >=1.14
    - openmm >=7.5.0
    - biopython
    - matplotlib
    - mdtraj
    - networkx >=2.0
    - openmm
    - pandas
    - parmed
    - pdbfixer
    - prody
    - pymol-open-source
    - pyopengl
    - pyqtgraph
    - pyqtwebengine
    - pyside2=5.13.2
    - pystache
    - pyvis

test:
  imports:
    - mdpertool

  requires:
    - pytest

  commands:
    - pytest -vv --pyargs mdpertool

about:
  home: "{{ url }}"
  license: BSD 3-Clause
  license_file: LICENSE.md
  license_family: BSD

  summary: {{ description }}
  description: "{{ long_description }}"
  dev_url: "{{ url }}"
  #doc_url: https://bio-otto.github.io/Bio-Otto/MDPerTool_GUI